flutter_src/README.md

- Flutter/Laravel
- Close #24
- README追記
なし。

エミュレーター起動方法　追記

---

laravel_vue/Makefile
laravel_vue/src/resources/js/pages/Home.vue
laravel_vue/src/resources/js/pages/Login.vue
laravel_vue/src/resources/js/pages/Register.vue

- Close #81 
- Composition APIのリファクタリング
- フロント系のmakeコマンド追加
なし。

Composition APIのリファクタリング

---

laravel_vue/src/app/Http/Controllers/MobileAuthController.php

- Close #85 
- バックエンドのエラーハンドリング修正
なし。

500エラーをハンドラーに投げる修正

---

laravel_vue/src/app/ApplicationServices/Admin/AuthApplicationService.php
laravel_vue/src/app/ApplicationServices/Admin/AuthApplicationServiceInterface.php
laravel_vue/src/app/ApplicationServices/AuthApplicationService.php
laravel_vue/src/app/ApplicationServices/AuthApplicationServiceInterface.php
laravel_vue/src/app/Http/Controllers/AuthController.php
laravel_vue/src/resources/js/store/auth.js
laravel_vue/src/routes/api.php
laravel_vue/src/routes/web.php
laravel_vue/src/tests/Feature/AuthController/GetLoginUserActionTest.php
laravel_vue/src/tests/Unit/ApplicationServices/AuthApplicationServiceTest.php

- Close #61 
- ログインユーザー取得APIの作成
- フロントの微修正
- リファクタリング
なし。

ログインユーザー取得API作成/実装

---

laravel_vue/src/tests/Feature/GroupController/IndexActionTest.php
laravel_vue/src/tests/Feature/TodoController/DestroyActionTest.php
laravel_vue/src/tests/Feature/TodoController/IndexActionTest.php
laravel_vue/src/tests/Feature/TodoController/StoreActionTest.php
laravel_vue/src/tests/Feature/TodoController/UpdateActionTest.php

- Close #45 
- TodoのCRUDのAPIのテストコード作成
仕様が決定していないガバガバのAPIのため、テストパターンを１つずつ作成したのみ。
仕様決定後に各テストパターンのテストコードを実装すること。

TodoのCRUDのAPIのテストコード作成

---

laravel_vue/src/composer.lock

- Close #100 
- php-cs-fixerのアップデート
要動作確認。

php-cs-fixerのバージョンをアップデート

---

flutter_src/lib/components/bottom_menu.dart
flutter_src/lib/components/menu.dart
flutter_src/lib/config/constants.dart
flutter_src/lib/pages/groups/index.dart
flutter_src/lib/pages/index.dart
flutter_src/lib/pages/user/show.dart

- Flutter/Laravel
- Close #101 
- Close #102 
- ボトムメニューの共通化
- バナー広告の共通化
なし。

ボトムメニューの共通化

---

src/app/Http/Controllers/Admin/UserController.php
src/resources/js/Admin.vue
src/resources/js/components/Alert.vue
src/resources/js/components/admin/Pagination.vue
src/resources/js/components/admin/SideMenu.vue
src/resources/js/pages/admin/Login.vue
src/resources/js/pages/admin/users/Index.vue
src/resources/js/router/index.js
src/resources/js/store/alert.js
src/resources/js/store/index.js
src/resources/sass/_admin.scss
src/resources/sass/_common.scss
src/routes/api.php

- Close #126 
- 管理者側　ユーザー一覧　作成
なし。

管理者側　ユーザー一覧　作成

---

src/app/Http/Controllers/Admin/UserController.php
src/app/Http/Requests/Admin/UpdateUserRequest.php
src/app/Http/Requests/StoreTodoRequest.php
src/app/Http/Requests/UpdateTodoRequest.php
src/resources/js/components/admin/Pagination.vue
src/resources/js/pages/admin/Login.vue
src/resources/js/pages/admin/users/Edit.vue
src/resources/js/pages/admin/users/Index.vue
src/resources/js/router/index.js
src/resources/js/store/alert.js
src/resources/sass/_admin.scss
src/tests/Feature/Admin/AuthController/InviteActionTest.php
src/tests/Feature/TodoController/StoreActionTest.php
src/tests/Feature/TodoController/UpdateActionTest.php

- Close #128 
- 管理者　ユーザー編集　作成
なし。

管理者　ユーザー編集　作成

---

src/app/Http/Controllers/Admin/TodoController.php
src/resources/js/pages/admin/todos/Index.vue
src/resources/js/router/index.js
src/routes/api.php

- Close #132 
- 管理者側　メモ一覧　作成
なし。

管理者側　メモ一覧　作成

---

src/app/Http/Controllers/Admin/TodoController.php
src/resources/js/pages/admin/todos/Edit.vue
src/resources/js/router/index.js
src/resources/sass/_admin.scss

- Close #134 
- 管理者側　メモ編集　作成
なし。

管理者側　メモ編集　作成

---

src/app/Http/Controllers/Admin/TodoController.php
src/resources/js/pages/admin/todos/Index.vue

- Close #136 
- 管理者側　メモ削除　作成
なし。

管理者側　メモ削除　作成

---

src/app/Http/Controllers/Admin/GroupController.php
src/resources/js/pages/admin/groups/Index.vue
src/resources/js/router/index.js
src/routes/api.php

- Close #138 
- 管理者側　グループ一覧　作成
なし。

管理者側　グループ一覧　作成

---

src/app/Http/Controllers/Admin/GroupController.php
src/resources/js/pages/admin/groups/Edit.vue
src/resources/js/pages/admin/todos/Edit.vue
src/resources/js/router/index.js

- Close #140 
- 管理者側　グループ編集　作成
なし。

管理者側　グループ編集　作成

---

src/app/Http/Controllers/Admin/GroupController.php
src/resources/js/pages/admin/groups/Index.vue

- Close #142 
- 管理者側　グループ削除　作成
なし。

管理者側　グループ削除　作成

---

src/app/Enums/InquiryStatus.php
src/app/Http/Controllers/Admin/InquiryController.php
src/app/Models/Inquiry.php
src/database/factories/InquiryFactory.php
src/database/migrations/2023_07_15_010146_create_inquiries_table.php
src/database/seeders/DatabaseSeeder.php
src/database/seeders/InquirySeeder.php
src/resources/js/pages/admin/inquiries/Index.vue
src/resources/js/router/index.js
src/routes/api.php

- Close #144 
- 管理者側　お問い合わせ一覧　作成
なし。

管理者側　お問い合わせ一覧　作成

---

src/app/Http/Controllers/Admin/InquiryController.php
src/app/Http/Requests/Admin/UpdateInquiryRequest.php
src/resources/js/pages/admin/inquiries/Edit.vue
src/resources/js/router/index.js
src/resources/sass/_admin.scss
src/routes/api.php

- Close #146 
- 管理者側　お問い合わせ編集　作成
なし。

管理者側　お問い合わせ編集　作成

---

src/app/Http/Controllers/Admin/AdminController.php
src/app/Http/Requests/Admin/UpdateAdminRequest.php
src/resources/js/pages/admin/admins/Edit.vue
src/resources/js/router/index.js

- Close #150
- 管理者側　管理者編集　作成
なし。

管理者側　管理者編集　作成

---

src/app/Http/Controllers/Admin/AdminController.php
src/app/Policies/AdminPolicy.php
src/app/Providers/AuthServiceProvider.php
src/resources/js/pages/admin/admins/Index.vue

- Close #152
- 管理者側　管理者削除　作成
なし。

管理者側　管理者削除　作成

---

src/app/Http/Controllers/Admin/ForgotPasswordController.php
src/app/Http/Controllers/Admin/ResetPasswordController.php
src/app/Http/Requests/Admin/PasswordResetRequest.php
src/app/Http/Requests/Admin/PasswordResetSendMailRequest.php
src/app/Http/Requests/Admin/PasswordUpdateRequest.php
src/app/Mail/Admin/PasswordResetMail.php
src/app/Models/Admin.php
src/composer.json
src/composer.lock
src/resources/js/Admin.vue
src/resources/js/components/admin/Header.vue
src/resources/js/pages/admin/ForgotPassword.vue
src/resources/js/pages/admin/Login.vue
src/resources/js/pages/admin/PasswordReset.vue
src/resources/js/pages/admin/PasswordUpdate.vue
src/resources/js/pages/admin/admins/Index.vue
src/resources/js/router/index.js
src/resources/sass/_admin.scss
src/resources/sass/_common.scss
src/resources/views/mails/admin/password_reset.blade.php
src/routes/api.php

- Close #154 
- 管理者側　パスワード変更・リセット　作成
なし。

管理者側　パスワード変更・リセット　作成

---

.github/PULL_REQUEST_TEMPLATE.md

プルリクのテンプレの修正

---

src/app/Http/Controllers/GroupController.php
src/app/Http/Requests/AddGroupUserRequest.php
src/app/Http/Requests/DeleteGroupUserRequest.php
src/app/Models/GroupUser.php
src/database/factories/GroupUserFactory.php
src/database/migrations/2023_01_30_002157_create_group_user_table.php
src/database/seeders/GroupUserSeeder.php
src/database/seeders/TodoSeeder.php
src/routes/api.php

- Close #160 
- グループのtodo一覧
- グループのユーザー一覧
- グループのユーザー追加
- グループのユーザー削除
なし。

ユーザー側のグループ詳細に関する処理の追加

---

src/app/Http/Controllers/MobileAuthController.php
src/routes/api.php

- Close #163 
- ログイン中ユーザーの取得APIの作成
なし。

ログイン中ユーザーの取得APIの作成

---

src/app/Http/Controllers/AuthController.php
src/app/Http/Controllers/GroupController.php
src/app/Http/Controllers/MobileAuthController.php
src/app/Http/Controllers/TodoController.php
src/app/Http/Controllers/UserController.php
src/app/Http/Requests/UpdateUserRequest.php
src/routes/api.php

- Close #115 
- マイページ編集の作成
なし。

マイページ編集の作成

---

src/app/Http/Controllers/InquiryController.php
src/app/Http/Requests/StoreInquiryRequest.php
src/app/Mail/InquiryToAdminsMail.php
src/app/Mail/InquiryToUserMail.php
src/database/migrations/2023_07_15_010146_create_inquiries_table.php
src/resources/views/mails/inquiry_to_admins.blade.php
src/resources/views/mails/inquiry_to_user.blade.php
src/routes/api.php

- Close #166 
- お問い合わせ新規登録の作成
なし。

お問い合わせ新規登録の作成

---

src/app/Http/Controllers/Admin/ResetPasswordController.php
src/app/Http/Controllers/MobileAuthController.php
src/app/Http/Controllers/UserController.php
src/app/Http/Requests/PasswordResetRequest.php
src/app/Http/Requests/PasswordResetSendMailRequest.php
src/app/Http/Requests/UpdatePasswordRequest.php
src/app/Mail/PasswordResetMail.php
src/app/Models/User.php
src/resources/js/User.vue
src/resources/js/components/admin/Footer.vue
src/resources/js/components/user/Header.vue
src/resources/js/pages/PasswordReset.vue
src/resources/js/pages/PasswordResetFinish.vue
src/resources/js/router/index.js
src/resources/sass/_admin.scss
src/resources/sass/_common.scss
src/resources/sass/_user.scss
src/resources/sass/app.scss
src/resources/views/mails/password_reset.blade.php
src/routes/api.php

- Close #168 
- パスワードリセット・変更の作成
なし。

パスワードリセット・変更の作成
